server:
  port: ${PORT:8761}

spring:
  application:
    name: eureka-server

## Eureka Server Configuration
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  instance:
    hostname: ${EUREKA_HOST:localhost}
  server:
    renewal-percent-threshold: 0.90